trigger:
  branches:
    include:
      - main  # Run on every push to main

pool:
  vmImage: 'ubuntu-latest'

# ✅ Enable Debug for Better Error Tracking
variables:
  System.Debug: true
  SIGN_FUNCTION_URL: "https://my-function-app26012004.azurewebsites.net/api/SignAndExport?code=rvAZsWPQvdCVgCnCGKop1ocVwh5okKv9oSNTHhgoth2yAzFul1duiA=="
  VERIFY_FUNCTION_URL: "https://my-function-app26012004.azurewebsites.net/api/VerifySignature?code=otiTTgpS5NMhUzTaD6Y7Ij82pWgDTlFNBejznqnMu9lmAzFuGDJgBg=="

stages:
  # ✅ Stage 1: Sign and Verify
  - stage: SignAndVerify
    displayName: "Sign and Verify Code"
    jobs:
      - job: SignAndVerifyJob
        displayName: "Sign and Verify Job"
        steps:
          # ✅ Step 1: Checkout Code
          - checkout: self
            fetchDepth: 1
            persistCredentials: true
            displayName: "Checkout Code"

          # ✅ Step 2: Debug Variables
          - script: |
              echo "🔍 Checking Variable Values..."
              echo "SIGN_FUNCTION_URL: $(SIGN_FUNCTION_URL)"
              echo "VERIFY_FUNCTION_URL: $(VERIFY_FUNCTION_URL)"
              echo "✅ Variables successfully loaded."
            displayName: "Debug Variables"

          # # ✅ Step 3: Zip the Code
          # - script: |
          #     echo "📦 Zipping the code..."
          #     zip -r code_to_sign.zip ./
          #     echo "✅ Code zipped successfully."
          #   displayName: "Zip the Code for Signing"

          # ✅ Step 4: Invoke Azure Function for Signing (With 3 Files)
          - task: PowerShell@2
            displayName: "Invoke Sign API using PowerShell (Binary Handling)"
            inputs:
              targetType: 'inline'
              script: |
                $url = "$(SIGN_FUNCTION_URL)"
                
                # ✅ Correct file paths
                $filePath = "$(System.DefaultWorkingDirectory)/code_to_sign.zip"
                $privateKeyPath = "$(System.DefaultWorkingDirectory)/private-key.asc"
                $passphrase = "dwee1234@@"  # Or use a secure variable
                
                # ✅ Check if files exist
                if (-Not (Test-Path $filePath)) {
                  Write-Error "❌ File not found: $filePath"
                  exit 1
                }
                if (-Not (Test-Path $privateKeyPath)) {
                  Write-Error "❌ Private key not found: $privateKeyPath"
                  exit 1
                }
                
                # ✅ Invoke API with files using -InFile (Binary Mode)
                Write-Output "✍️ Invoking Azure Function to Sign..."
                $outputZipPath = "$(System.DefaultWorkingDirectory)/output.zip"
                
                $form = @{
                  file = Get-Item -Path $filePath
                  privateKeyFile = Get-Item -Path $privateKeyPath
                  passphrase = $passphrase
                }
                
                # 🚀 Invoke Sign API with Multipart Form Data
                Invoke-RestMethod -Uri $url -Method Post -Form $form -OutFile $outputZipPath
                
                # ✅ Check if signed file is created
                if (-Not (Test-Path $outputZipPath)) {
                  Write-Error "❌ Signed file not received. Check Azure Function logs."
                  exit 1
                }
                
                Write-Output "✅ Code signed and saved to output.zip successfully."

          # ✅ Step 5: Publish Signed Artifact
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/output.zip"
              artifactName: "output"
            displayName: "Publish Signed Artifact"

          # ✅ Step 8: Open output.zip and Modify ModbusTCPMaster.zip
          - script: |
              echo "📂 Unzipping output.zip..."
              unzip -o output.zip -d temp_dir
              echo "✅ Unzip Complete"
          
              echo "📂 Unzipping code_to_sign.zip from extracted content..."
              if [ -f "temp_dir/code_to_sign.zip" ]; then
                unzip -o temp_dir/code_to_sign.zip -d temp_dir/code_to_sign
                echo "✅ code_to_sign.zip extracted successfully"
              else
                echo "❌ Error: code_to_sign.zip not found!"
                exit 1
              fi
          
              echo "📝 Modifying package_config.json..."
              PACKAGE_CONFIG="temp_dir/code_to_sign/package_config.json"
              
              # Check if the file exists
              if [ -f "$PACKAGE_CONFIG" ]; then
                # Modify the content (Example: Add a new field or update an existing one)
                rm "$PACKAGE_CONFIG"
                echo "✅ package_config.json modified successfully"
              else
                echo "❌ Error: package_config.json not found!"
                exit 1
              fi
          
              echo "📦 Zipping code_to_sign content again..."
              cd temp_dir/code_to_sign
              zip -r signed_code.zip .
              mv code_to_sign.zip ../
              cd ../..
          
              echo "📦 Replacing modified code_to_sign.zip in output.zip..."
              cd temp_dir
              zip -r ../output.zip *
              cd ..
              echo "✅ output.zip updated successfully"
            displayName: "Open, Modify & Re-zip code_to_sign.zip"
          
          # ✅ Step 9: Verify Updated output.zip Existence
          - script: |
              if [ -f "output.zip" ]; then
                echo "✅ Updated output.zip found successfully"
              else
                echo "❌ Error: Updated output.zip not found!"
                exit 1
              fi
            displayName: "Verify Updated output.zip"

          # ✅ Step 6: Invoke Azure Function for Verification
          - task: PowerShell@2
            displayName: "Invoke Verify API using PowerShell (Raw Data)"
            inputs:
              targetType: 'inline'
              script: |
                # ✅ Define API URL and File Path
                $url = "$(VERIFY_FUNCTION_URL)"
                $signedCodePath = "$(System.DefaultWorkingDirectory)/output.zip"
                
                # ✅ Check if File Exists
                if (-Not (Test-Path $signedCodePath)) {
                    Write-Error "❌ Signed file not found: $signedCodePath"
                    exit 1
                }
                
                # ✅ Prepare HTTP Headers for API Call
                $headers = @{
                    "Content-Type" = "application/octet-stream"  # Use this for raw binary zip
                }
                  
                $form = @{
                  file = Get-Item -Path $signedCodePath
                }
                
                # ✅ Send Raw Binary Data Using Invoke-RestMethod
                try {
                    Write-Output "🔎 Invoking Azure Function to Verify with Raw Binary Data..."
                    
                    # 🚀 Sending raw binary zip using -InFile
                    $response = Invoke-RestMethod -Uri $url -Method Post -Form $form
                    
                    # ✅ Check if Verification was Successful
                    Write-Output "🔎 Verification Response: $response"
                    
                    if ($response -match "Signature verified successfully") {
                        Write-Output "✅ Verification successful. File is authentic."
                    }
                    else {
                        Write-Error "❌ Verification failed! Possible tampering detected."
                        exit 1
                    }
                }
                catch {
                    # ✅ Capture Detailed Error Information
                    Write-Error "❌ Error invoking Verify API: $_"
                    exit 1
                }

          # ✅ Step 7: Publish Verified Output (output.zip)
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/output.zip"
              artifactName: "output_zip"
            displayName: "Publish Verified Output (output.zip)"

  # ✅ Stage 2: Deploy
  - stage: Deploy
    displayName: "Deploy Signed Code"
    dependsOn: SignAndVerify
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: "Deploy Signed Code"
        steps:
          # ✅ Step 8: Download Verified Output Artifact
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: "output_zip"
              targetPath: "$(System.DefaultWorkingDirectory)/output"
            displayName: "Download Verified Output Artifact"

          # ✅ Step 9: Deploy Verified Output to Azure App Service
          - script: |
              echo "🚀 Deploying verified output to Azure App Service..."
              az webapp deployment source config-zip \
                --resource-group myResourceGroup \
                --name my-web-app \
                --src "$(System.DefaultWorkingDirectory)/output/output.zip"
              echo "✅ Deployment completed successfully."
            displayName: "Deploy Verified Output"
